FORMAT: 1A
HOST: http://v3.api.sysapp.bid

# sysbetv3 API

Documentação para os desenvolvedores que estão integrando seus aplicativos a plataforma de eventos desportivos.
A utilização não deve ocorrer sem aviso prévio do autor e seu concentimento. Entre em contato em caso de dúvidas.

## Firebase Array
A estrutura de dados utilizados no firebase mira a performace. Por isso ele implementa a array de forma alternativa a array de um objeto json. [Firebase Arrays](https://firebase.google.com/docs/database/web/lists-of-data)

## Fianlizando o cliente
Lembre-se de remover o listner como boa prática quando sua aplicação cliente for finalizada ou tiver mudança de contexto. [Remover Listner](https://firebase.google.com/docs/database/web/read-and-write#detach_listeners)
# Group Seguranca

# ENTRAR [POST /Sec/SignIn]
Após conseguir o token de autenticação é necessário validar utilizando a biblioteca do firebase. O token retornado pela validação do firebase deve ser mantido para futuras requisições as demais partes da API e o token de autenticação da chamada deve ser descartado. [Custom Auth](https://firebase.google.com/docs/auth/web/custom-auth).

```
    //javascript
    firebase.auth().signInWithCustomToken(token).catch(function(error) {
    // Handle Errors here.
    var errorCode = error.code;
    var errorMessage = error.message;
    // ...
    });
```
+ Request (application/x-www-form-urlencoded)

    + Attributes
        + grant_type: password
        + username - nome do usuario para autenticar
        + pin_code - codigo pin da empresa
        + password (string) - senha
    
    + Body

            grant_type:password&password:[password]&username:[username]&pin_code:[pin_code]
        
+ Response 200 (application/json)

        {
            //TODO identificar parametros
        }

# PIN [GET /pins/{pinCode}]

+ Parameters
    + pinCode (number) - Código PIN para acesso aos parametros da banca

+ Response 200 (application/json)

    + Attributes
        + nome (string)
        + uid (string)
        + tenant (string)
        + cover (string) - URL da imagem da logo

# Group Financeiro

# Saldo [/bancarios/{username}/saldo]
Resumo do saldo do usuário no ciclo atual da movimentação financeira. Utilizando os recursos do firebase você pode registrar um ouvidor para sempre manter seu saldo atualizado em seu cliente.
```
var saldoRef = firebase.database().ref('/bancarios/teste@tenant/saldo');
saldoRef.on('value', function(snapshot) {
  atualizarSaldo(snapshot.val());
});
```

+ Parameters
    + username: teste@tenant (string) - nome totalmente qualificado do usuario

## GET

+ Response 200 (application/json)

    + Attributes (Saldo)

# Lancamentos [/lancamentos/{username}/ciclo{?limitToFirst,startAt}]
Lista de lançamentos realizados na conta financeira do usuario
Devido ao alto volume de dados utilize sempre o limitador e faça paginação. Também permaneça escutando alterações para evitar o numero de chamadas excessivas. [Filtrar e Ordernar Firebase](https://firebase.google.com/docs/database/web/lists-of-data?authuser=0#sorting_and_filtering_data)

+ Parameters
    + limitToFirst (number) - quantidade maxima
    + startAt (number) - filtro de inicio de atributos

## GET

+ Response 200 (application/json)

    + Attributes (array[Lancamento])

## Resumo da Movimentações [GET /movimentacaos/{username}/resumo]

+ Response 200 (application/json)

    + Attributes (MovimentacaoResumo)


# Group Eventos

# Group Aposta
O ciclo para se realizar uma aposta envolve solicitar o proximo código do bilhete. Salvar as informações da solicitação do bilhete e por último solicitar a confirmação do bilhete. A imagem abaixo ilustra o processo da solicitação.
[Processo De Bilhete](http://yuml.me/47ccd375.png) . A API exbosta abaixo faz suporte ao processo de bilhete.

## Bilhetes [GET /movimentacaos/{username}/ciclo]

+ Response 200 (application/json)

    + Attributes (array[BilheteResumo])

## Bilhete [/bilhetes/{codigo}]
Restricões de Seguranca impedem a consulta a lista de bilhetes. Toda consulta deve ser realizda a apenas um bilhete.

+ Parameters
    + codigo (string) - Codigo do bilhete

## GET
+ Response 200 (application/json)

    + Attributes (BilheteCompleto)

## POST
Para salbar o bilhete é essencial conhecer o processo de escrever no banco de dados do firebase. [Ler e Escrever Dados Firebase](https://firebase.google.com/docs/database/web/read-and-write#basic_write). O usuario persiste o dados de forma autonama e solicita a confirmação do bilhete.
O mesmo não sofre alterações caso o bilhete já tenha sido confirmado.

```
    let bilhete = {
        ...dadosBilhete
    };

    database.ref('bilhetes').child(codigo).set(bilhete)
    .then(() => { alert('salvo com sucesso'); });
```
+ Request (application/json)

    + Attributes(BilheteBase)

+ Response 201 (application/json)

# CouponNext [POST /Cupom/CouponNext/]

+ Request

    + Headers
            
            Authorization: 'Bearer TOKEN' (string) - Token de autorização para realizar autorização

+ Response 201 (application/json)

            {
                "codigo": "XX-DDDDDD-WWWW"
            }

# CheckOut [POST /Cupom/CheckOut/{codigo}]
Faz *checkout* do cupom validando suas informações e calculando os dados.
Caso tenha algum erro ao processar a solicitação é retornado o `STATUS CODE` `422` com a informação do erro.
É necessário informar o cupom no corpo do Request

+ Request (application/json)

    + Headers
            
            Authorization: 'Bearer TOKEN' (string) - Token de autorização para realizar autorização

    + Body
    
            {
                "codigo": "XX-DDDDDD-WWWW"
            }

+ Response 422 (application/json)

            {
                "error": "mensagem"
            }

+ Response 200 (plain/text)

            "Sucesso"

# Data Structures

## identificado (object)
+ id (string) - identificador unico do recurso

## BilheteBase (identificado)
+ cliente (string)
+ codigo (string)
+ valorAposta (string)
+ palpites (array)

## MetadataBilhete (identificado)
+ valorAposta (number)
+ valorPremio (number)
+ bilhete (string)
+ totalTaxa (number)
+ apostaUnica (boolean)
+ confirmacao (boolean)
+ username (string)
+ tenant (string)
+ quantidadePalpites (number)
+ comissao (object) - Objeto de informação da comissão

## BilheteCompleto (BilheteBase)
+ metadata (MetadataBilhete)
+ taxas (object)

## BilheteResumo (MetadataBilhete)
+ codigo (string)

## MovimentacaoResumo (identificado)
+ bilheteAbertoTotal (number)
+ bilheteEncerradoTotal (number)
+ bilhetePremiadoTotal (number)
+ bilheteCanceladoTotal (number)
+ cicloInicio (number)

## Saldo (identificado)
+ credito (number) - Valores de credito da movimentacao financeira
+ debito (number) - Valores de debito da movimentacao financeira
+ moeda (number) - Quantidade disponivel do valor para aposta

## Lancamento (identificado)
+ movimentacao: CREDITO, DEBITO (enum)
+ origem
+ quando
+ tipo (string) - Determina o tipo da origem do lançamento
+ ts (number) - timestamp da data do lançamento
+ valor (number) - Valor do lançamento
+ saldo (Saldo)