FORMAT: 1A
HOST: http://v3.api.sysapp.bid

# sysbetv3 API

Documentação para os desenvolvedores que estão integrando seus aplicativos a plataforma de eventos desportivos.
A utilização não deve ocorrer sem aviso prévio do autor e seu concentimento. Entre em contato em caso de dúvidas.

# Group Seguranca

# ENTRAR [POST /Sec/SignIn]
Após conseguir o token de autenticação é necessário validar utilizando a biblioteca do firebase. O token retornado pela validação do firebase deve ser mantido para futuras requisições as demais partes da API e o token de autenticação da chamada deve ser descartado. [Custom Auth](https://firebase.google.com/docs/auth/web/custom-auth).

```
    //javascript
    firebase.auth().signInWithCustomToken(token).catch(function(error) {
    // Handle Errors here.
    var errorCode = error.code;
    var errorMessage = error.message;
    // ...
    });
```
+ Request (application/x-www-form-urlencoded)

    + Attributes
        + grant_type: password
        + username - nome do usuario para autenticar
        + pin_code - codigo pin da empresa
        + password (string) - senha
    
    + Body

            grant_type:password&password:[password]&username:[username]&pin_code:[pin_code]
        
+ Response 200 (application/json)

        {
            //TODO identificar parametros
        }

# Group Financeiro

# Saldo [/bancarios/{username}/saldo]
Resumo do saldo do usuário no ciclo atual da movimentação financeira.

+ Parameters
    + username: teste@tenant (string) - nome totalmente qualificado do usuario

## GET

+ Response 200 (application/json)

    + Attributes (Saldo)
    
# Group Eventos

# Group Movimentação

# Data Structures

## identificado (object)
+ id (string) - identificador unico do recurso

## Saldo (identificado)
+ credito (number) - Valores de credito da movimentacao financeira
+ debito (number) - Valores de debito da movimentacao financeira
+ moeda (number) - Quantidade disponivel do valor para aposta
